name: Automatic PR Review with AI

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
  pull_request_review_comment: # Novo gatilho para comentários em revisões de PR

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: 106d079459ea49ddb72ce23748e28698
          AZURE_API_TYPE: "azure"
          AZURE_API_VERSION: "2023-05-15"
          AZURE_API_BASE: "https://teste-pr-agent.openai.azure.com"
          AZURE_DEPLOYMENT_ID: "bf665bca-a16f-41c0-bd7e-b1d78a4be422"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
